
#  ♻️  OPTIMIZING HAZARDOUS WASTE MANAGEMENT FACILITIES IN THE PHILIPPINES: ADDRESSING REGIONAL DISPARITIES

This project utilizes **Folium** and **GeoPandas** to visualize, analyze, and interpret hazardous waste management data across the Philippines through interactive mapping and geospatial analysis techniques.

## Project Overview

This project aims to analyze the total hazardous waste generated by various regions in the country and compare it with the number of registered Treatment, Storage, and Disposal (TSD) facilities.

By examining this relationship, the study determines whether there is a complementary balance between hazardous waste generation and facility availability. Through geospatial visualization and regional comparison, the project identifies areas with possible shortages, overconcentration, or inconsistencies in hazardous waste management infrastructure.

The analysis highlights potential gaps and disparities in hazardous waste management across the Philippines, which can help guide future strategies for environmental sustainability, policy development, and infrastructure enhancement.

##  🎯 Objectives

- Analyze hazardous waste generation per region
- Compare waste generation with existing TSD facilities
- Visualize regional disparities using interactive maps
- Identify regions with insufficient hazardous waste management facilities
- Support data-driven environmental planning and sustainability initiatives

## Technologies Used

- Python
- Folium
- GeoPandas
- Pandas
- Jupyter Notebook / Google Colab

## Expected Outcome

The project provides a clearer understanding of how hazardous waste management facilities are distributed relative to waste generation across regions in the Philippines. The findings may assist in improving environmental management strategies and promoting balanced regional development.
